title: 文章列表
description: My Personal Stack Problems
author: PasseRR
github: https://github.com/PasseRR
about: I'm a javaer.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-weibo
      link: "#"
    - icon: fa-github
      link: "https://github.com/PasseRR"

share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/

url: "https://passerr.github.io"
baseurl: ""
paginate: 15
per_page: 15
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
