title: PasseRR's Blog

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

url: "https://passerr.github.io"
baseurl: ""
paginate: 18
paginate_path: "/blogs/:num.html"

highlighter: rouge
redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough

gems:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

remote_theme: PasseRR/jekyll-blog-theme

bmob-app-id: e71fdd8d5b1f139b1da542a1e3a2ad09
bmob-rest-key: 3f399f018571ea78c9bc3245c58a8c0e

# google分析衡量id
ga: G-1L1DPX3PFD
# 百度统计id
hm: 712de58e89ed55d7c9e9bbd30ad340cd

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
