title: PasseRR's Blog

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

baseurl: ""
permalink: /:name:output_ext
paginate: 20
paginate_path: "/blogs/:num.html"

# markdown render engine.
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough

gems:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
  - jekyll-sitemap
  - jekyll-relative-links

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

relative_links:
  enabled:     true
  collections: true

tipue_search:
  include:
    pages: true
  exclude:
    files: [ 404.md, search.md ]

remote_theme: PasseRR/jekyll-blog-theme

# 留言板配置
bmob-app-id: e71fdd8d5b1f139b1da542a1e3a2ad09
bmob-rest-key: 3f399f018571ea78c9bc3245c58a8c0e
bmob-message-table: message

# google分析gtag
ga: G-1L1DPX3PFD
# 百度统计hm
hm: 6fcc00740d8cd30d91522810ec50075d

url: "https://www.xiehai.zone"
# 主题静态资源cdn前缀
#theme-cdn: https://gcore.jsdelivr.net/gh/PasseRR/jekyll-blog-theme
# 博客静态资源cdn前缀
#cdn: https://gcore.jsdelivr.net/gh/PasseRR/passerr.github.io

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-relative-links
