title: PasseRR's Blog
description: My Personal Blog
author: PasseRR
github: https://github.com/PasseRR
about: I'm a javaer.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
  - icon: fa-github
    link: "https://github.com/PasseRR"
  - icon: fa-weibo
    link: "http://weibo.com/u/1015039932"
  - icon: fa-facebook
    link: "#"
  - icon: fa-twitter
    link: "#"
  - icon: fa-linkedin
    link: "#"

share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
  - text: 关于
    url: /about/

url: "https://passerr.github.io"
baseurl: ""
paginate: 15
per_page: 15
paginate_path: "/page/:num/"

highlighter: pygments
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
