name: Resource Submit CI

on:
  push:
    branches:
      - master
  # 每天定时索引
  schedule:
    - cron: '0 23 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      # 遍历sitemap文件中的url
      - id: sitemaps
        name: Fetch Sitemap Files
        run: |
          echo "urls<<EOF" >> $GITHUB_ENV
          for line in $(curl -s https://www.xiehai.win/sitemap_index.xml | grep -oP "(?<=<loc>)[^<]+")
            do
              echo "$(curl -s ${line} | grep -oP "(?<=<loc>)[^<]+")" >> $GITHUB_ENV
            done
          echo "EOF" >> $GITHUB_ENV
      # 百度url提交
      - name: Submit Baidu Urls
        run: >
          curl -X POST -s -d '${{ env.urls }}'
          'http://data.zz.baidu.com/urls?site=https://www.xiehai.win&token=${{ secrets.BAIDU_KEY }}'
      # 必应url提交
      - name: Submit Bing Urls
        run: >
          origin=$(<<EOF 
          
          ${{ env.urls }}
          
          EOF
          
          )
          
          jsonUrls=`echo -e $origin | awk '{x[i++]=$0} END{for (j=0; j<i;) print "\""x[j++]"\"" (j==i?"":",")}'`
          
          curl -H 'Content-Type: application/json; charset=utf-8' -X POST -s -d 
          "{\"siteUrl\": \"https://www.xiehai.win\", \"urlList\": [$jsonUrls]}" 
          'https://www.bing.com//webmaster/api.svc/json/SubmitUrlbatch?apikey=${{ secrets.BING_KEY }}'
