name: Resource Submit CI

on:
  push:
    branches:
      - master
  # 每天定时索引
  schedule:
    - cron: '0 23 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - id: sitemaps
        name: Fetch Sitemap Files
        run: |
          urls=''
          curl -s https://www.xiehai.win/sitemap_index.xml | grep -oP "(?<=<loc>)[^<]+" | while read line
          do
            urls+=$(curl -s ${line} | grep -oP "(?<=<loc>)[^<]+" | awk '{print ""$0"\n"}')
          done
          echo '::set-output name=urls::$urls'
          
      # 百度url提交 | awk '{print "\""$0"\","}'
      - name: Submit Baidu Urls
        run: >
          curl -X POST -s -d '${{ join(steps.sitemaps.outputs.urls, '\n') }}'
          'http://data.zz.baidu.com/urls?site=https://www.xiehai.win&token=${{ secrets.BAIDU_KEY }}'
      # 必应url提交
      - name: Submit Bing Urls
        run: >
          curl -H 'Content-Type: application/json; charset=utf-8' -X POST -s -d 
          '{"siteUrl": "https://www.xiehai.win", "urlList": [${{ toJson(steps.sitemaps.outputs.urls) }}]}' 
          'https://www.bing.com//webmaster/api.svc/json/SubmitUrlbatch?apikey=${{ secrets.BING_KEY }}'
        